### PR TITLE
Add Void Linux icons

### PR DESCRIPTION
**Pull request by PosaLusa24**

### CODE REVIEW

**Comment by bobafetthotmail** [comment]
the second commit is just deleting the png images, not replacing them. Please fix that and I'll merge this PR

**Comment by bobafetthotmail** [comment]
how did you generate the images in the "optipng-generated" commit? I would like to edit the script and instructions so all images are done like that.

**Comment by PosaLusa24** [comment]
Ah actually, I meant to say "script-generated pngs" in the second commit; they were generated by running ./render-bitmap.sh (which uses optipng). The initial pngs in the first commit were exported manually from Inkscape (because clumsy me didn't notice the contribution instructions).

**Comment by bobafetthotmail** [comment]
thanks, merged

**Comment by PosaLusa24** [comment]
your welcome!

**Pull request merged**
