### PR TITLE
Add os_astos icons

### PR DESCRIPTION
**Pull request by randalthor17**
Add icons for [astOS](https://github.com/CuBeRJAN/astOS), an immutable Arch based distribution utilizing btrfs snapshots. Have been using this for a while, thought I'd open a PR.

### CODE REVIEW

**Comment by randalthor17** [comment]
Might need a small color change, although I'm not sure which color would match both themes.

**Comment by bobafetthotmail** [comment]
Yeah I can't merge this as it's not visible with dark/black backgrounds.

You can just add a white background to the icon (similar to Android Apps) so that no matter what is the theme the icon is readable.

**Comment by randalthor17** [comment]
Thanks for the feedback, gonna update soon.

**Comment by randalthor17** [comment]
Should I just give it a background or do something like this, where the logo with the background is inside an about 96x96 px rectangle?
os_astos

**Comment by randalthor17** [comment]
Also, this is what I came up with the Bedrock logo. Is it okay-ish?
bedrock_blackbg

**Comment by randalthor17** [comment]
Also, the logo for astOS has changed, and this is what I got.
os_astos

**Comment by randalthor17** [comment]
Done, thanks for the feedback, learned a lot from this PR.

**Comment by bobafetthotmail** [comment]
Thanks, merged

**Pull request merged**
