### PR TITLE
Add os_cachy icons

### PR DESCRIPTION
**Pull request by botatooo**
[CachyOS](https://cachyos.org/) is a user-friendly and highly optimized distribution based on Arch Linux. I was able to use [this svg](https://cachyos.org/_astro/logo.5dd65b4e.svg) as a base for the svg I've submitted.

### CODE REVIEW

**Comment by botatooo** [comment]
`os_cachy` just rings better. If you don't mind, since I've got more than one commit, can you squash this PR? Thanks.

**Comment by bobafetthotmail** [comment]
the file name is used by refind to select the right icon for the OS (it does look into the initramfs or kernel or somewhere to identify the distro and the name of the icon after the "os_" has to match that). I don't know if it works with both 
os_cachyos and os_cachy.

If you confirm that it actually works, I will merge it

**Comment by bobafetthotmail** [comment]
whatever, merged. If someone complains about this OS icon looking wrong we will figure it out then

**Comment by ProjectInfinity** [comment]
> whatever, merged. If someone complains about this OS icon looking wrong we will figure it out then

I am the bearer of bad news. My install doesn't seem to be detected as Cachy at all.

Here's the os-release.

cat /etc/os-release
NAME="CachyOS Linux"
PRETTY_NAME="CachyOS"
ID=cachyos
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://cachyos.org/"
DOCUMENTATION_URL="https://wiki.cachyos.org/"
SUPPORT_URL="https://forum.cachyos.org/"
BUG_REPORT_URL="https://github.com/cachyos"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=cachyos

**Comment by botatooo** [comment]
Seems like os_cachy wasn't the correct one, but os_cachyos. Sorry about that!

Mar 23, 2023 6:58:39 PM Infinity ***@***.***>:

**Comment by bobafetthotmail** [comment]
should be fixed now with https://github.com/bobafetthotmail/refind-theme-regular/commit/99b1681914edbd7f82e757274041de459f217c76
as I have renamed the icons into os_cachyos

I also added a line in the instruction about choosing the right name for the icons by looking at /etc/os-release

**Pull request merged**
